version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - QDRANT_URL=http://qdrant:6333
  #   depends_on:
  #     - qdrant
  #   volumes:
  #     - ./data:/app/data

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8501:8501"
  #   environment:
  #     - BACKEND_URL=http://backend:8000
  #   depends_on:
  #     - backend

volumes:
  qdrant_storage:
